name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy source code to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/Digital-Transformation-Leaders-2023/frontend"

      - name: Export secrets to remote environment and Run Docker Image on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export VITE_API_URL=${{ secrets.VITE_API_URL }}
            export VITE_MOCKS=${{ secrets.VITE_MOCKS }}
            yarn install
            yarn build
            yarn start
